Document: wicrawl
Title: Debian wicrawl Manual
Author: <insert document author here>
Abstract: This manual describes what wicrawl is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/wicrawl/wicrawl.sgml.gz

Format: postscript
Files: /usr/share/doc/wicrawl/wicrawl.ps.gz

Format: text
Files: /usr/share/doc/wicrawl/wicrawl.text.gz

Format: HTML
Index: /usr/share/doc/wicrawl/html/index.html
Files: /usr/share/doc/wicrawl/html/*.html

  
