package UI::GTKWarbar;

my $frame; # pointer to hold content generated by this module

my $basedir="/usr/local/wicrawl";
my $image_dir = "$basedir/ui/pix";

# Global variables for warbar
my $warbar_buffer;
my $colorbar;

sub generate {
		$frame = Gtk2::Frame->new;
		my $warbox = Gtk2::VBox->new;

		$warbar_buffer = Gtk2::Label->new();
		$warbar_buffer->set_markup("<span weight='bold'>w a r b a r</span>");
		$warbar_buffer->set_justify('center');
		$warbox->pack_start($warbar_buffer,FALSE,FALSE,0);	

		$colorbar = Gtk2::Label->new();
		$colorbar->set_justify('fill');

		my $colorbar_setup = "<span background='black'>";
		my $width = 200;
		for(my $i=0; $i < $width; $i++) { $colorbar_setup .= " "; }
		
		$colorbar_setup .= "</span>";
		$colorbar->set_markup($colorbar_setup);
		$warbox->pack_start($colorbar,FALSE,FALSE,0);

		$frame->add($warbox);		

		return $frame;			
}

sub show_data {		

	# adding rows with APs
	my @APS = UI::Common->get_ap;

	my $wepcount = 0;
	my $packets = 0;
	my $totalap = 0;

	my $haveinternet = 0;
	my $newap = 0;
	my $ip = 0;
	my $associated = 0;
	foreach (@APS) {
		#collect statistical information
		$totalap++;
		$packets += $_->{PACKETS};
		if($_->{ENCRYPTION} eq "WEP") {$wepcount++}
		if($_->{EVENT} eq "have-internet") {$haveinternet++}
		elsif($_->{EVENT} eq "new-ap") {$newap++}
		elsif($_->{EVENT} eq "associated") {$associated++}
		elsif($_->{EVENT} eq "have-ip") {$ip++}
	}

	if($totalap) {

	my $ratio = int($wepcount*100/$totalap);	

	my $msg = "<span weight='bold'>";
	$msg .= "Total APs: $totalap\t";
	$msg .= "Encrypted: $wepcount\t";
	$msg .= "Ratio: $ratio%\t";
	$msg .= "Packets: $packets\t";
	$msg .= "</span>";
	$warbar_buffer->set_markup($msg);

	# colorbar
	my $width = 200;
	my $colorbar_newap = int($newap/$totalap*$width);
	my $colorbar_associated = int($associated/$totalap*$width);
	my $colorbar_ip = int($ip/$totalap*$width);
	my $colorbar_internet = int($haveinternet/$totalap*$width);

	# now let's generate a bar
	my $colorbar_markup = "<span background = 'black' foreground='white'>";
	my $unknown_state = $width - $colorbar_newap - $colorbar_associated - $colorbar_ip - $colorbar_internet;
	my $unknown_number = $totalap - $newap - $associated - $ip - $haveinternet;
	for(my $i=0; $i < $unknown_state; $i++) { 
		if($i == int($unknown_state/2)) {
			if($unknown_number) {
				$colorbar_markup .= "$unknown_number"; 
			}
		}
		else {$colorbar_markup .= " "; }
	}
	$colorbar_markup .= "</span>";

	#newap info
	$colorbar_markup .= "<span background = 'red' foreground = 'white'>";
	for(my $i = 0; $i < $colorbar_newap; $i++) { 
		if($i == int($colorbar_newap/2)) {$colorbar_markup .= "$newap"; }
		else {$colorbar_markup .= " "; } 
	}
	$colorbar_markup .= "</span>";

	#associated info
	$colorbar_markup .= "<span background = 'orange' foreground='white'>";
	for(my $i = 0; $i < $colorbar_associated; $i++) { 
		if($i == int($colorbar_associated/2)) {$colorbar_markup .= "$associated"; }
		else {$colorbar_markup .= " "; } 
	}
	$colorbar_markup .= "</span>";

	#have-ip info
	$colorbar_markup .= "<span background = 'blue' foreground='white'>";
	for(my $i = 0; $i < $colorbar_ip; $i++) { 
		if($i == int($colorbar_ip/2)) {$colorbar_markup .= "$ip"; }
		else {$colorbar_markup .= " "; } 
	}
	$colorbar_markup .= "</span>";

	#have-internet info
	$colorbar_markup .= "<span background = 'darkgreen' foreground='white'>";
	for(my $i = 0; $i < $colorbar_internet; $i++) { 
		if($i == int($colorbar_internet/2)) {$colorbar_markup .= "$haveinternet"; }
		else {$colorbar_markup .= " "; } 
	}
	$colorbar_markup .= "</span>";


	$colorbar->set_markup($colorbar_markup);
	
	} else {
		$warbar_buffer->set_markup("<span weight='bold'>Scanning...</span>");
	}
}

sub show {
	$frame->show_all;
}

sub hide {
	$frame->hide_all;

	# Perform window resizing
	my $window = $frame->get_parent->get_parent;
	my ($width, $height) = $window->get_size;
	$window->resize($width, $height - 50);
}

1;
