#!/usr/bin/perl -w
#
#   GUI interface for wicrawl
#
#   wicrawl - A modular and thorough wi-fi scanner
#   http://midnightresearch.com/projects/wicrawl - for details
#
#   Original Code:  Peter Kacherginsky (iphelix)
#   Contributors:  Aaron Peterson
#
#   Copyright (C) 2005-2006 Midnight Research Laboratories
#
#   THIS SOFTWARE IS PROVIDED "AS IS". NO WARRANTY IS ASSUMED.
#   NO LIABILITY OF ANY KIND FOR ANY DAMAGES WHATSOEVER RESULTING
#   FROM THE USE OF THIS SOFTWARE WILL BE ACCEPTED. IT CAN BURN
#   YOUR HARD DISK, ERASE ALL YOUR DATA AND BREAK DOWN YOUR
#   MICROWAVE OVEN. YOU ARE ADVISED.
#
#   wicrawl is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.  For details see doc/LICENSE.


use strict;
use File::Basename;
use IO::Pipe;
use XML::Smart;
use FileHandle;


use Gtk2 -init;
use Glib qw(TRUE FALSE);
use Gtk2::SimpleList;
use Gtk2::Helper;

use MIME::Base64;

# AUTOFLUSH
#$|=1;tim

my $basedir;

# Set basedir here so we can set the lib path dynamically.
BEGIN { 
	$basedir="@@BASEDIR@@/";
}

use lib "$basedir/include/perl/";
use Preferences;
use AccessPoint;
use Profile;
use Plugin;

use UI::Common;
use UI::Reports;

use UI::GTKMenubar;
use UI::GTKWarbar;
use UI::GTKView;
use UI::GTKOutput;

# Set UI type
UI::Common->guitype('gtk');

# Check to make sure that the effective user id is 0. got root?
if($> != 0) {
	print "\n [!!] Sorry you need to be root to run this\n";
	exit 1;
}

#######################################################################
# User Interface Section
###################
my $window = Gtk2::Window->new('toplevel');
$window->signal_connect('delete_event' => sub {
	UI::GTKExecute->stop;
	Gtk2->main_quit; 
});
$window->set_title("Wicrawl - Midnight Research Labs");
$window->set_icon_from_file("$basedir/ui/pix/Mrl.jpg");

my $vbox = Gtk2::VBox->new;
$vbox->pack_start(UI::GTKMenubar->generate,FALSE,FALSE,0);
$vbox->pack_start(UI::GTKWarbar->generate, FALSE, FALSE, 0);

my $pane = Gtk2::VPaned->new;
$pane->add1(UI::GTKView->generate);
$pane->add2(UI::GTKOutput->generate);
$pane->child1_resize (1);

$vbox->pack_start($pane,TRUE,TRUE,0);


$vbox->show_all();

$window->add($vbox);
$window->show();

# yeah kids, no p0wning w/o permission ;)
my $warn=" [!!!] Wicrawl is a tool intended for security professionals, Please\n";
$warn.="act responsibly.  Use the SSID filters to scan only devices you control [!!!]\n\n";
UI::GTKOutput->lprint(2,1, $warn);

Gtk2->main();
